<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * package    Netzarbeiter_CustomerRegIp
 * copyright  Copyright (c) 2014 Vinai Kopp http://netzarbeiter.com/
 * license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/* @var $this Netzarbeiter_CustomerRegIp_Block_Adminhtml_Customer_Edit_Tab_View_Regip_Lookup */
?>
<?php $info = $this->getInfo() ?>
<table cellspacing="2" class="box-left">
	<tr>
		<td><?php echo $this->__('IP:') ?></td>
		<td><?php echo $this->htmlEscape($info->getIp()) ?></td>
	</tr>
	<tr>
		<td><?php echo $this->__('DNS Lookup:') ?></td>
		<td><?php echo $this->htmlEscape($this->resolveDnsAddr($info->getIp())) ?></td>
	</tr>
	<tr>
		<td><?php echo $this->__('Country:') ?></td>
		<td><?php echo $this->htmlEscape($info->getCountryName()) ?> (<?php echo $this->htmlEscape($info->getCountry()) ?>)</td>
	</tr>
	<tr>
		<td><?php echo $this->__('Region:') ?></td>
		<td><?php echo $this->htmlEscape($info->getRegion()) ?></td>
	</tr>
	<tr>
		<td><?php echo $this->__('City:') ?></td>
		<td><?php echo $this->htmlEscape($info->getCity()) ?></td>
	</tr>
	<tr>
		<td><?php echo $this->__('Postcode:') ?></td>
		<td><?php echo $this->htmlEscape($info->getPostcode()) ?></td>
	</tr>
</table>