<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * package    Netzarbeiter_CustomerRegIp
 * copyright  Copyright (c) 2014 Vinai Kopp http://netzarbeiter.com/
 * license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/* @var $this Netzarbeiter_CustomerRegIp_Block_Adminhtml_Customer_Edit_Tab_View_Regip */
?>
<div class="entry-edit">
    <div class="entry-edit-head"><h4 class="icon-head head-customer-view-remoteip">
	<?php if ($this->isCustomerCreatedInAdmin()): ?>
		<?php echo $this->__('Admin IP during creation') ?>
	<?php else: ?>
		<?php echo $this->__('Remote IP during registration') ?>
	<?php endif; ?>
	</h4></div>
    <fieldset>
        <table cellspacing="2" class="box-left">
            <tr>
                <td><strong><?php echo $this->__('Remote Address:') ?></strong> <?php echo $this->getCustomerRegIpHtml() ?></td>
				<?php if ($this->isValidIp()): ?>
				<td>
					<?php if ($this->isIpInfoDbEnabled()): ?>
					<button onclick="customerRegIp.lookup(); return false;"
							title="<?php echo $this->__('Check the location of %s via AJAX', $this->getCustomerRegIp()) ?>"><span><?php echo $this->__('IPInfoDB Lookup') ?></span></button>
					<?php endif; ?>
					<button onclick="window.open('http://www.ip2location.com/<?php echo $this->getCustomerRegIp() ?>','lookup',''); return false;"
							title="<?php echo $this->__('Check the location of %s in a popup', $this->getCustomerRegIp()) ?>"><span><?php echo $this->__('ip2location.com Lookup') ?></span></button>
				</td>
				<?php endif; ?>
            </tr>
        </table>
        <div id="customerregip-lookup-result" style="display: none;"></div>
    </fieldset>
	<script type="text/javascript">
if (typeof CustomerRegIp=='undefined') {
	var CustomerRegIp = Class.create({
		initialize: function(){
			this.url = '<?php echo $this->getAjaxLookupUrl() ?>';
			this.targetId = 'customerregip-lookup-result';
		},
		lookup: function(){
			$(this.targetId).show();
			new Ajax.Updater(this.targetId, this.url);
		}
	});
}
var customerRegIp = new CustomerRegIp();
	</script>
</div>